#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=${JAVA_HOME}/bin:${PATH}
 
cd $OPENSHIFT_REPO_DIR

./gradlew clean jar