#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
source $OPENSHIFT_CARTRIDGE_SDK_BASH

set -x

export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=${JAVA_HOME}/bin:${PATH}
 
cd $OPENSHIFT_REPO_DIR && cd ../dependencies

if [[ -n `ps -A | grep java` ]]; then
	pkill -SIGTERM java
fi

java -jar spark-*.jar &